version: "3.8"
name: shuffler

services:
  shuffler-postgres:
    container_name: shuffler-postgres
    image: postgres:15.2-alpine
    volumes:
      - postgres-db:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SHUFFLER_DB_NAME}
      POSTGRES_PORT: ${SHUFFLER_DB_PORT}
      POSTGRES_PASSWORD: ${SHUFFLER_DB_PASSWORD}
    expose:
      - "5432"
    ports:
      - "8432:5432"
    networks:
      - shuffler

  shuffler-redis:
    container_name: shuffler-redis
    image: redis:7.0.9-alpine
    environment:
      REDIS_PASSWORD: ${SHUFFLER_REDIS_PASSWORD}
    ports:
      - "8479:6379"
    expose:
      - "6379"
    networks:
      - shuffler

  shuffler:
    container_name: shuffler
    build:
      dockerfile: Dockerfile
    environment:
      SHUFFLER_BOT_TOKEN: ${SHUFFLER_BOT_TOKEN}
      SHUFFLER_REDIS_PASSWORD: ${SHUFFLER_REDIS_PASSWORD}
      SHUFFLER_DB_PASSWORD: ${SHUFFLER_DB_PASSWORD}
    env_file:
      - .env
    networks:
      - shuffler
    depends_on:
      - shuffler-postgres
      - shuffler-redis

volumes:
  postgres-db:
    name: ${SHUFFLER_DB_NAME}

networks:
  shuffler:
    driver: bridge
