version: "3.7"
name: shuffler

services:
  shuffler:
    container_name: shuffler
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - shuffler-postgres
      - shuffler-redis
    depends_on:
      - shuffler-postgres
      - shuffler-redis

  shuffler-postgres:
    container_name: shuffler-postgres
    image: postgres:15.2-alpine
    volumes:
      - postgres-db:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SHUFFLER_DB_NAME}
      POSTGRES_PASSWORD: ${SHUFFLER_DB_PASSWORD}
    ports:
      - "8432:5432"

  shuffler-redis:
    container_name: shuffler-redis
    image: redis:7.0.9-alpine
    environment:
      REDIS_PASSWORD: ${SHUFFLER_REDIS_PASSWORD}
    ports:
      - "8479:6379"

volumes:
  postgres-db:
    name: ${SHUFFLER_DB_NAME}
