logging:
  level:
    ru.acuma.shuffler: DEBUG
    org.hibernate: ERROR
telegram:
  bot:
    name: ${SHUFFLER_BOT_NAME}
    token: ${SHUFFLER_BOT_TOKEN}
spring:
  main:
    web-application-type: none
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        cache:
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_second_level_cache: true
          use_query_cache: true
  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SHUFFLER_DB_SERVER_HOST:localhost}:${SHUFFLER_DB_SERVER_PORT:5432}/${SHUFFLER_DB_NAME:shuffler_local}${SHUFFLER_DB_URL_PARAMS:}
    username: ${SHUFFLER_DB_USER:local}
    password: ${SHUFFLER_DB_PASSWORD:root}
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  data:
    redis:
      host: ${SHUFFLER_REDIS_HOST:localhost}
      port: ${SHUFFLER_REDIS_PORT:6379}
      password: ${SHUFFLER_REDIS_PASSWORD:root}
      repositories:
        enabled: false
application:
  client:
    word-generator:
      url: ${SHUFFLER_WORD_GENERATOR_API:https://random-word-api.herokuapp.com}
  statistics:
    url: ${SHUFFLER_STATISTICS_HOST:localhost:3000}
  users:
    root: ${SHUFFLER_ROOT_USERS}
  media:
    location: ${SHUFFLER_MEDIA_LOCATION:/media/avatar/}
