telegram:
  bot:
    name: ${SHUFFLER_BOT_NAME}
    token: ${SHUFFLER_BOT_TOKEN}

spring:
  main:
    web-application-type: none
  jpa:
    properties:
      hibernate:
        default_schema: public
  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SHUFFLER_DB_SERVER_HOST:localhost}:${SHUFFLER_DB_SERVER_PORT:5432}/${SHUFFLER_DB_NAME:shuffler_local}${SHUFFLER_DB_URL_PARAMS:}
    username: ${SHUFFLER_DB_USER:local}
    password: ${SHUFFLER_DB_PASSWORD:root}
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  data:
    redis:
      host: ${SHUFFLER_REDIS_HOST:localhost}
      port: ${SHUFFLER_REDIS_PORT:6379}
      password: ${SHUFFLER_REDIS_PASSWORD:root}

application:
  media:
    location: ${SHUFFLER_MEDIA_LOCATION:/media/avatar/}
    link: ${SHUFFLER_AVATAR_PATH:https://shuffler.fun/avatar/}

rating:
  calibration:
    games: ${SHUFFLER_CALIBRATION_GAMES:9}
    enemies: ${SHUFFLER_CALIBRATION_ENEMIES:3}
    multiplier: ${SHUFFLER_CALIBRATION_MULTIPLIER:6}
    game-penalty: ${SHUFFLER_CALIBRATION_PENALTY_MULTIPLIER:0.5}
