telegram:
  bot:
    name: ${SHUFFLER_BOT_NAME}
    token: ${SHUFFLER_TOKEN}

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SHUFFLER_DB_SERVER_HOST:localhost}:${SHUFFLER_DB_SERVER_PORT:5432}/${SHUFFLER_DB_NAME:shuffler_local}${SHUFFLER_DB_URL_PARAMS:}
    username: ${SHUFFLER_DB_USER:local}
    password: ${SHUFFLER_DB_PASSWORD:root}
  flyway:
    out-of-order: false
    enabled: true
    locations:
      - classpath:db/migration

application:
  media:
    location: ${SHUFFLER_MEDIA_LOCATION:/media/avatar/}
    link: ${SHUFFLER_AVATAR_PATH:https://shuffler.fun/avatar/}

rating:
  team-build-strategy: ${SHUFFLER_TEAM_BUILD_STRATEGY:random}
  calibration:
    games: ${SHUFFLER_CALIBRATION_GAMES:10}
    enemies: ${SHUFFLER_CALIBRATION_ENEMIES:5}
    multiplier: ${SHUFFLER_CALIBRATION_MULTIPLIER:6}
    game-penalty: ${SHUFFLER_CALIBRATION_PENALTY_MULTIPLIER:0.5}