telegram.bot:
  name: "trgb"
  token: ${TRGB_TOKEN}

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${TRGB_DB_SERVER_HOST:localhost}:${TRGB_DB_SERVER_PORT:5432}/${TRGB_DB_NAME:trgb}${TRGB_DB_URL_PARAMS:}
  username: ${TRGB_DB_USER:trgb}
  password: ${TRGB_DB_PASSWORD:root}

spring.flyway:
  out-of-order: false
  enabled: true
  locations:
    - classpath:db/migration

server:
  port: ${TRGB_PORT:6509}
  forward-headers-strategy: native
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true
  tomcat:
    max-connections: 10000
    threads:
      max: 1000
      min-spare: 50


